### ISSUE TITLE
Admin: add index page definitions for each role

### ISSUE THREAD

**Issue by forsetius** [forsetius/rpg#1]
In Forseti/AdminBundle change:
`ROLE_SUPER_ADMIN: { User: all, Group: all }`

into:
```
ROLE_SUPER_ADMIN: 
    access: { User: all, Group: all }
    index_page: Users
    label: easyAdmin.role.superadmin.name
```

- [ ] Decide between "index_page", "starting_entity" or inbetween.
- [ ] `label`s are to be merged from `roles.def`
- [ ] Fix new config layout in Security\*
